import type { Metadata } from 'next';
import { Figtree, Geist_Mono, Geist } from 'next/font/google';
import './globals.css';
import AppHeader from '@/components/AppHeader/AppHeader';
import AppSidebar from '@/components/AppSidebar';
import { cn } from '@/lib/utils';
import { QueryProvider } from '@/providers/query-provider';
import { AuthProvider } from '@/providers/auth-provider';
import { ModalProvider } from '@/providers/modal-provider';
import { Toaster } from '@/components/ui/sonner';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

const figtree = Figtree({
  variable: '--font-figtree',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full',
        'antialiased',
        figtree.variable,
        geistMono.variable,
        'font-sans',
        geist.variable,
      )}
    >
      <body>
        <QueryProvider>
          <AuthProvider>
            <ModalProvider>
              <div className="min-h-screen block sm:flex bg-gray-900 font-base text-base-gray-light pb-12 md:pb-0">
                <AppSidebar />
                <div className="flex flex-col flex-1 pb-12 sm:pb-0">
                  <AppHeader />
                  <main className="flex-1 overflow-y-auto p-4 w-full max-w-[1200px] mx-auto">
                    {children}
                  </main>

                  <Toaster />
                </div>
              </div>
            </ModalProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
